# Generated by Django 4.0.3 on 2022-03-23 19:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_images_alter_product_id_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.URLField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
